### ISSUE TITLE
XSD schemas alternative

### ISSUE THREAD

**Issue by Dragas** [cyanpotion/x8l#4]
The main drawing point of XML is XSD files. XSD files define the structure of XML document and they're used at parsing level to determine whether or not the file has a valid structure. Does your format have an alternative to this?

If not, it cannot replace XML in any meaningful way.

**Comment by XenoAmess** [comment]
@Dragas
Hi.

> The main drawing point of XML is XSD files. 

I have no idea what is the word "drawing point" you mean here.
But I guess you want to say XSD is important or something.
Actually, not always.
For example, json do have a json schema, but not everybody/every-usecases need to use it.
XSD is used mainly on (IMO) multilanguage project, for describing how data are structured in some xml in one time, to avoid migration.
Yes it is useful anyway, but I don't think it is that important to xml.
At least nearly all of usecases from me myself do not need XSD.
(and to be honest XSD is toooo verbose.)
Ah, that does not mean we don't wanna support XSD. Read down for more details.
Btw, I hate DTD, so I will never try to make this repo support DTD. 

> Does your format have an alternative to this? 

No, I don't want to change XSD's schema.
Actually in my opinion, XSD is not part of XML, but it is more like a usage of xml, or something based on xml, which pre-defined what key/value pair should have meaning of what thing. (kindof like XHTML, ha.)
And the data of XSD are saved as data in format of XML.
So, instead of change XSD schema, I'd prefer convert the content structure of XSD from XML to X8L.
For example, XSD like this are original saved as XML like this:
```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">
    <xs:element name="note">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="to" type="xs:string"/>
                <xs:element name="from" type="xs:string"/>
                <xs:element name="heading" type="xs:string"/>
                <xs:element name="body" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
```

And we can convert it to X8L format.

```
<xs:schema xmlns:xs=http://www.w3.org/2001/XMLSchema
           targetNamespace=http://www.w3school.com.cn
           xmlns=http://www.w3school.com.cn
           elementFormDefault=qualified>
    <xs:element name=note>
        <xs:complexType>
            <xs:sequence>
                <xs:element name=to type=xs:string>>
                <xs:element name=from type=xs:string>>
                <xs:element name=heading type=xs:string>>
                <xs:element name=body type=xs:string>>
            >
        >
    >
>
```

And I do think all the meaningful data of XSD can remain after the convertion, at least in theory.

**But**, unfortunally, it actually is not supported well yet.
Reason is simple: the dependency I used to parse XML file is dom4j, and dom4j seems have bugs in dealing with XSD files.
When we tried to parse XSD files as XML, it will aoto-detect it (wrongly) thus throws an exception.
I have made an issue about this in https://github.com/dom4j/dom4j/issues/93 , and hope they can solve it soon.
(but seems they have not even solved the last bug I committed, so we might have to wait for another several months. *sigh.)

Fortunately, the X8L->XSD(XML) conversion is good, so if you write XSD in X8L, you can convert it into XSD(XML) correctly. (At least I and my test cases think it can.)

Also, as all known, toolchains of X8L is actually lack.
So if you really want to use XSD's checkers on X8L, you might better cast both the data file and schema file to xml first.
Of course that should be easy. Just use class X8LDealer to load it and write it with XMLDealer to a stream/string.

**Comment by XenoAmess** [comment]
Close as resolved.
If you have any more questions about this / about other things, you can either reopen it or create a new issue.

**Comment by XenoAmess** [comment]
@Dragas 
Hi.
Now (I think) that bug I mentioned is fixed (actually, we did not fix it but evaded from it).

**Comment by XenoAmess** [comment]
Hi.
We created a demo which migh be useful to this issue.
It shows exactly how we can maintain XSD data in x8l format.
see https://github.com/XenoAmess/x8l_spring_context
